version: '3.4'

services:
  db:
    image: postgres
    restart: always
    env_file: .env
    build:
      context: ./docker/db/
    ports:
      - '8432:5432'
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data:
    external: false
